{% set version = "1.8rc1" %}
{% set variant = "openblas" %}

package:
  name: openturns
  version: {{ version }}

source:
  fn: openturns-{{ version }}.tar.gz
  url: https://github.com/openturns/openturns/archive/v{{ version }}.tar.gz
  sha1: f4085571cdc743b2c1b5ce7ec8bd4c8ea22b254e

build:
  number: 200
  skip: true  # [win]
  features:
    - blas_{{ variant }}
  detect_binary_files_with_prefix: True

requirements:
  build:
    - python
    - cmake
    - swig
    - boost
    - blas 1.1 {{ variant }}
    - openblas 0.2.18*
    - libxml2
    - muparser
    - tbb
    - nlopt
    - hmat-oss

  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas 0.2.18*
    - libxml2
    - muparser
    - tbb
    - nlopt
    - hmat-oss

test:
  imports:
    - openturns

about:
  home: http://openturns.org/
  license: LGPLv3
  summary: Uncertainty treatment library

extra:
  recipe-maintainers:
    - jschueller
